version: '3.8'

volumes:
  elasticsearch:


networks:
  elk:


services:
  elasticsearch:
    image: elasticsearch:8.7.0
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    networks:
      - elk
  kibana:
    image: kibana:8.7.0
    networks:
      - elk
  nginx_for_elk:
    image: nginx
    ports:
      - 9200:9200
      - 5601:5601
    networks:
      - elk
    volumes:
      - type: bind
        source: /home/my-user/elk-stack/nginx.conf
        target: /etc/nginx/nginx.conf
      - type: bind
        source: /home/my-user/elk-stack/.htpasswd
        target: /etc/nginx/.htpasswd
